name: CI

on:
  push:
  pull_request:
  schedule:
  - cron:  '1 0 * * 0'

jobs:
  test-voms-atlas:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      if: "!(startsWith(github.ref, 'refs/tags/'))"
      uses: docker/build-push-action@v1
      with:
        repository: kratsg/voms-atlas
        dockerfile: voms-atlas/Dockerfile
        path: voms-atlas
        tags: test
        tag_with_sha: true
        tag_with_ref: true
        push: false
    - name: List Built Images
      run: docker images

  test-clang-format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      if: "!(startsWith(github.ref, 'refs/tags/'))"
      uses: docker/build-push-action@v1
      with:
        repository: kratsg/clang-format
        dockerfile: clang-format/Dockerfile
        path: clang-format
        tags: test
        tag_with_sha: true
        tag_with_ref: true
        push: false
    - name: List Built Images
      run: docker images

  test-eos-krb5:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker image
      if: "!(startsWith(github.ref, 'refs/tags/'))"
      uses: docker/build-push-action@v1
      with:
        repository: kratsg/eos-krb5
        dockerfile: eos-krb5/Dockerfile
        path: eos-krb5
        tags: test
        tag_with_sha: true
        tag_with_ref: true
        push: false
    - name: List Built Images
      run: docker images
