name: Publish Docker Images

on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  publish-voms-atlas:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build and Publish to Registry
      if: "!(startsWith(github.ref, 'refs/tags/'))"
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kratsg/voms-atlas
        dockerfile: voms-atlas/Dockerfile
        path: voms-atlas
        tags: latest
    - name: Build and Publish to Registry with Release Tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kratsg/voms-atlas
        dockerfile: voms-atlas/Dockerfile
        path: voms-atlas
        tags: latest,latest-stable
        tag_with_ref: true

  publish-eos-krb5:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build and Publish to Registry
      if: "!(startsWith(github.ref, 'refs/tags/'))"
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kratsg/eos-krb5
        dockerfile: eos-krb5/Dockerfile
        path: eos-krb5
        tags: latest
    - name: Build and Publish to Registry with Release Tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kratsg/eos-krb5
        dockerfile: eos-krb5/Dockerfile
        path: eos-krb5
        tags: latest,latest-stable
        tag_with_ref: true
